### ISSUE TITLE
article mentions example of MAIL_URL but there is no example

### ISSUE THREAD

**Issue by webmagnets** [meteor/galaxy-docs#13]
On this page -> https://github.com/meteor/galaxy-docs/blob/master/content/environment-variables.md

It says this:

```
The following is an example setting for the MAIL_URL environment variable: smtp://postmaster%40your.mailserver.address.com:password@mailserver.smtp.address.com:587

settings.json example

{
  "galaxy.meteor.com": {
    "env": {
      "MONGO_URL": "...",
      "MONGO_OPLOG_URL": "..."
    }
  },
  ... other keys can go here
}
```

but there is no example. Plus, I think `... other keys can go here` might be missing some braces.

**Comment by julianeon** [comment]
Thank you for your feedback. The Environment Variables article has been edited to be more in line with your recommendations. If you have any other comments, let us know!
