### ISSUE TITLE
DNS setup in AWS Route 53 is missing information

### ISSUE THREAD

**Issue by tschneid** [meteor/galaxy-docs#226]
When following the instructions for [redirecting the root domain](https://github.com/meteor/galaxy-docs/blob/master/source/dns.md#redirecting-the-root-domain) to the `www` subdomain in the Galaxy docs, I couldn't get it to work with HTTPS.

After some digging into the AWS docs, it seems like redirecting HTTPS is not possible with this simple setup described in the Galaxy docs.
> The sites must use HTTP, because the redirect can't connect to Amazon S3 over HTTPS.
> https://aws.amazon.com/premiumsupport/knowledge-center/redirect-domain-route-53/

The solution for me was to add a CloudFront distribution (and a new cert) and point the `A` record of the root domain to that (instead of pointing it to the S3 bucket).
> Amazon S3 website endpoints do not support HTTPS or access points. If you want to use HTTPS, you can use Amazon CloudFront to serve a static website hosted on Amazon S3.
> https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteEndpoints.html

Did I miss anything here? The AWS docs seem to contradict the Galaxy docs.

**Comment by filipenevola** [comment]
See two possible solutions [here](https://github.com/meteor/galaxy-docs/pull/233)
