### ISSUE TITLE
No info on how to actually contact support in Support section

### ISSUE THREAD

**Issue by tomyo** [meteor/galaxy-docs#5]
> All Galaxy customers can submit support cases from within Galaxy and receive Basic online support for deployment-related questions. There is no guaranteed response SLA for Basic support but questions are typically answered within 1-2 business days.

How to contact support is not specified. :/
At least explain how to 'submit support cases'.

Thanks.

**Comment by danahmadi** [comment]
Thanks for the suggesstion @tomyo!
